# Generated by Django 5.2.12 on 2026-04-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogress",
            name="awaiting_practice_answer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="last_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="last_topic",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
