# Generated by Django 5.2.12 on 2026-04-05 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_userprogress_last_answer_userprogress_last_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='difficulty',
            field=models.CharField(default='foundation', max_length=20),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='subject',
            field=models.CharField(default='maths', max_length=50),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='awaiting_remediation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='practice_difficulty',
            field=models.CharField(default='foundation', max_length=20),
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('last_outcome', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='whatsapp_bot.userprogress')),
            ],
            options={
                'unique_together': {('user', 'subject', 'topic')},
            },
        ),
    ]
