# Generated by Django 5.2.12 on 2026-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0003_practicequestion_difficulty_practicequestion_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='session_correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='session_total_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
