# Generated by Django 5.2.12 on 2026-04-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0004_userprogress_session_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='lesson_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson_subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
