# Generated by Django 5.2.12 on 2026-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0005_userprogress_lesson_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='low_data_mode',
            field=models.BooleanField(default=True),
        ),
    ]
