# Generated by Django 5.2.12 on 2026-04-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0007_learningpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLearningPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('transcript', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('duration_label', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
