# Generated by Django 5.2.12 on 2026-04-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0008_audiolearningpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='offline_mode',
            field=models.BooleanField(default=False),
        ),
    ]
