# Generated by Codex on 2026-04-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0002_userprogress_user_and_phone_nullable"),
        ("whatsapp_bot", "0009_userprogress_offline_mode"),
    ]

    operations = []
