services:
  - type: web
    name: eduaccess
    env: python
    plan: free
    rootDir: eduaccess
    buildCommand: "./build.sh"
    startCommand: "gunicorn eduaccess.wsgi --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "eduaccess-whatsapp-bot-4hg5.onrender.com,eduaccess.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://eduaccess-whatsapp-bot-4hg5.onrender.com,https://eduaccess.onrender.com"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "EduAccess <noreply@eduaccess.app>"
      - key: PYTHON_VERSION
        value: "3.10.16"
